---
version: '3'
services:
  ripro-vis:
    image: patrickriegler/ripro-vis
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: ripro-vis-app
    ports: ['8081:8081']
#    volumes:
#      - .api/:/usr/src/ripro-vis/
#    extra_hosts: 
#     - "elasticsearch:${AWSIP}"
    environment:
#     - WSURL=${AWSIP}
#     - WSPORT=1337
     - SERVERNAME=ec2-35-158-69-241.eu-central-1.compute.amazonaws.com
     - PORT=8081
     - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
     - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
     - APIKEY=${APIKEY}
     - SECRETKEY=${SECRETKEY}
#    logging:
#      driver: gelf
#      options:
#        gelf-address: udp://${AWSIP}:12201
#        tag: "websocket"
#      driver: "json-file"
#      options:
#        max-size: "200k"
#        max-file: "10"


  ripro-vis-demonstrator:
    image: patrickriegler/ripro-vis-demonstrator
    build:
      context: ./demonstrator
      dockerfile: Dockerfile
    container_name: ripro-vis-demonstrator-app
    ports: 
       - '8082:80'
       - '8083:443'
#    volumes:
#      - .api/:/usr/src/ripro-vis/
#    extra_hosts: 
#     - "elasticsearch:${AWSIP}"
    environment:
     - SERVERNAME=ec2-35-158-69-241.eu-central-1.compute.amazonaws.com
     - PORT=8081
#     - APIKEY=${APIKEY}
#     - SECRETKEY=${SECRETKEY}
#     - WSURL=${AWSIP}
#     - WSPORT=1337
#    logging:
#      driver: gelf
#      options:
#        gelf-address: udp://${AWSIP}:12201
#        tag: "websocket"
#      driver: "json-file"
#      options:
#        max-size: "200k"
#        max-file: "10"


