---
version: '3'
services:
  ripro-vis:
    image: patrickriegler/ripro-vis
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: ripro-vis-app
    ports: ['8081:8081']
#    volumes:
#      - .api/:/usr/src/ripro-vis/
#    extra_hosts: 
#     - "elasticsearch:${AWSIP}"
    environment:
#     - WSURL=${AWSIP}
#     - WSPORT=1337
     - PORT=8081
     - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
     - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
#    logging:
#      driver: gelf
#      options:
#        gelf-address: udp://${AWSIP}:12201
#        tag: "websocket"
#      driver: "json-file"
#      options:
#        max-size: "200k"
#        max-file: "10"


